#!/usr/bin/env bash

# Extract Java SE download from Oracle into this project's java
# folder then...
# ln -s java/<extracted folder> java/default
JAVA_HOME=java/default
PATH=$JAVA_HOME/bin:$PATH

# We start app using nohup so that the app will continue running
# when we log out nohup logs any output to nohup.out and so we
# remove any old nohup.out
if [ -e "nohup.out" ]
then
	rm nohup.out
fi

# Package the app ready for running in production
# Should add "clean" before "stage" if want to clean
./activator stage
if [ "$?" != "0" ]; then
	echo "Could not stage app" 1>&2
	exit 1
fi

# Run in background using nohup (so we can log out without stopping it)
# without New Relic
nohup ./target/universal/stage/bin/benfletcher-com -DapplyEvolutions.default=true &
# with New Relic
#nohup ./target/universal/stage/bin/benfletcher-com -DapplyEvolutions.default=true -J-javaagent:newrelic/newrelic.jar -J-Dnewrelic.config.file=newrelic/newrelic.yml &

# nohup.out gets created a bit later so we'll sleep before we tail it
sleep 2

# Can CTRL+C when we've seen enough
tail -f nohup.out
